#### ROUTES FOR LOCALHOST

# GET (READ) TEST: Get all customers - This request produces a json object for data for all customers.
GET http://localhost:3000/customers HTTP/1.1

###

# GET (READ) TEST: Get customer by id - This request produces a json object for a single customer when appending ?id=someIdFromSingleCustomer to /customers/.
GET http://localhost:3000/customers/68f44922b43746b12b968028 HTTP/1.1

###

# POST (CREATE) TEST: Create customer - Reference: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
POST http://localhost:3000/customers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Hello",
  "lastName": "You",
  "email": "helloyou@gmail.com",
  "billingAddress": {
    "street": "120 S State St",
    "city": "Bluffdale",
    "state": "UT",
    "zip": "84020",
    "country": "US"
  },
  "shippingAddress": {
    "street": "120 S State St",
    "city": "Bluffdale",
    "state": "UT",
    "zip": "84020",
    "country": "US"
  },
  "phone": "801-458-8567"
}
###

# PUT (UPDATE) TEST: Update customer by id
PUT http://localhost:3000/customers/68f4525ed063df9e13f44097 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Shlenae",
  "lastName": "McBride",
  "email": "shlenaemcbride@gmail.com",
  "billingAddress": {
    "street": "120 S State St",
    "city": "Sandy",
    "state": "UT",
    "zip": "84017",
    "country": "US"
  },
  "shippingAddress": {
    "street": "120 S State St",
    "city": "Sandy",
    "state": "UT",
    "zip": "84017",
    "country": "US"
  },
  "phone": "801-456-8567"
}

###

# DELETE (DELETE) TEST: Delete customer by id
DELETE http://localhost:3000/customers/68f45390d063df9e13f440a0 HTTP/1.1

#### ROUTES FOR RENDER

# GET (READ) TEST: Get all customers - This request produces a json object for data for all customers.
GET https://lds-sheet-music.onrender.com/customers HTTP/1.1

###

# GET (READ) TEST: Get customer by id - This request produces a json object for a single customer when appending ?id=someIdFromSingleCustomer to /customers/.
GET https://lds-sheet-music.onrender.com/customers/68f44922b43746b12b968028 HTTP/1.1

###

# POST (CREATE) TEST: Create customer - Reference: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
POST https://lds-sheet-music.onrender.com/customers HTTP/1.1
Content-Type: application/json

{
  "firstName": "Hello",
  "lastName": "You",
  "email": "helloyou@gmail.com",
  "billingAddress": {
    "street": "120 S State St",
    "city": "Bluffdale",
    "state": "UT",
    "zip": "84020",
    "country": "US"
  },
  "shippingAddress": {
    "street": "120 S State St",
    "city": "Bluffdale",
    "state": "UT",
    "zip": "84020",
    "country": "US"
  },
  "phone": "801-458-8567"
}
###

# PUT (UPDATE) TEST: Update customer by id
PUT https://lds-sheet-music.onrender.com/customers/68f4525ed063df9e13f44097 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Shlenae",
  "lastName": "McBride",
  "email": "shlenaemcbride@gmail.com",
  "billingAddress": {
    "street": "120 S State St",
    "city": "Sandy",
    "state": "UT",
    "zip": "84017",
    "country": "US"
  },
  "shippingAddress": {
    "street": "120 S State St",
    "city": "Sandy",
    "state": "UT",
    "zip": "84017",
    "country": "US"
  },
  "phone": "801-456-8567"
}

###

# DELETE (DELETE) TEST: Delete customer by id
DELETE https://lds-sheet-music.onrender.com/customers/68f45390d063df9e13f440a0 HTTP/1.1